web/router.ex
defmodule Handsup.Router do
  use Handsup.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Handsup.Session, repo: Handsup.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Handsup do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/groups", GroupController, param: "name_eng" do
      resources "/events", EventController, only: [:new, :create]
    end
    resources "/events", EventController, except: [:new, :create]
  end

  scope "/auth", Handsup do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Handsup do
  #   pipe_through :api
  # end
end

web/models/group.ex
defmodule Handsup.Group do
  @moduledoc """
  Group
  """
  use Handsup.Web, :model

  alias Handsup.User

  schema "groups" do
    field :name_eng, :string
    field :name, :string
    belongs_to :organizer, User
    many_to_many :users, User, join_through: "groups_users"

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  @spec changeset(map, map) :: map
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name_eng, :name])
    |> validate_required([:name_eng, :name])
    |> validate_format(:name_eng, ~r/^[\w_-]+$/i)
    |> unique_constraint(:name_eng)
  end
end

# TODO: Move it somewhere
defimpl Phoenix.Param, for: Handsup.Group do
  def to_param(%{name_eng: name_eng}) do
    name_eng
  end
end

web/controllers/group_controller.ex
defmodule Handsup.GroupController do
  use Handsup.Web, :controller

  alias Handsup.Group
  import Handsup.Session, only: [authenticate_user: 2]

  plug :authenticate_user when action in [:new, :edit,
                                          :create, :update, :delete]

  def index(conn, _params) do
    groups = Repo.all(Group)
    render conn, "index.html", groups: groups
  end

  def show(conn, %{"name_eng" => name_eng}) do
    group = Repo.get_by!(Group, name_eng: name_eng)
    render conn, "show.html", group: group
  end

  def new(conn, _params) do
    changeset = Group.changeset(%Group{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"group" => group_params}) do
    changeset =
      conn.assigns.current_user
      |> build_assoc(:own_groups)
      |> Group.changeset(group_params)

    case Repo.insert(changeset) do
      {:ok, _group} ->
        conn
        |> put_flash(:info, "Group created successfully.")
        |> redirect(to: group_path(conn, :index))
        |> halt
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"name_eng" => name_eng}) do
    group =
      conn.assigns.current_user
      |> user_own_groups
      |> Repo.get_by!(name_eng: name_eng)
    changeset = Group.changeset(group)
    render conn, "edit.html", changeset: changeset, group: group
  end

  def update(conn, %{"name_eng" => name_eng, "group" => group_params}) do
    user = conn.assigns.current_user
    group = Repo.get_by!(user_own_groups(user), name_eng: name_eng)
    changeset = Group.changeset(group, group_params)

    case Repo.update(changeset) do
      {:ok, _group} ->
        conn
        |> put_flash(:info, "Group updated successfully.")
        |> redirect(to: group_path(conn, :index))
      {:error, changeset} ->
        render(conn, "edit.html", group: group, changeset: changeset)
    end
  end

  def delete(conn, %{"name_eng" => name_eng}) do
    user = conn.assigns.current_user
    group = Repo.get_by(user_own_groups(user), name_eng: name_eng)

    case group && Repo.delete(group) do
      {:ok, _group} ->
        redirect_to_index(conn, "Group destroyed successfully.")
      {:error, _changeset} ->
        redirect_to_index(conn, "Group isn't destroyed successfully.")
      _ ->
        redirect_to_index(conn, "You don't own this group.")
    end
  end

  defp user_own_groups(user) do
    assoc(user, :own_groups)
  end

  defp redirect_to_index(conn, msg) do
    conn
    |> put_flash(:info, msg)
    |> redirect(to: group_path(conn, :index))
    |> halt
  end
end

web/views/group_view.ex
defmodule Handsup.GroupView do
  use Handsup.Web, :view
end

web/templates/group/edit.html.eex
<h2>Edit group</h2>

<%= render "form.html", changeset: @changeset,
                        action: group_path(@conn, :update, @group) %>

<%= link "Back", to: group_path(@conn, :index) %>

web/templates/group/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :name_eng, "Name Eng(used as url)", class: "control-label" %>
    <%= text_input f, :name_eng, class: "form-control" %>
    <%= error_tag f, :name_eng %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/group/index.html.eex
<h1>Listing groups</h1>

<table>
  <%= for group <- @groups do %>
    <tr>
      <td><%= group.name %></td>
      <td><%= group.name_eng %></td>
      <td><%= link("show", to: group_path(@conn, :show, group)) %></td>
      <td><%= link("edit", to: group_path(@conn, :edit, group)) %></td>
      <td><%= link("delete", to: group_path(@conn, :delete, group), method: :delete) %></td>
    </tr>
  <% end %>
</table>

<%= link "New Group", to: group_path(@conn, :new) %>

web/templates/group/new.html.eex
<h2>New Group</h2>

<%= render "form.html", changeset: @changeset,
                        action: group_path(@conn, :create) %>

web/templates/group/show.html.eex
<h2>Show group</h2>

<p>Name: <%= @group.name %></p>
<p>Name Eng: <%= @group.name_eng %></p>

<%= link "New event", to: group_event_path(@conn, :new, @group.name_eng) %>
<%= link "Back", to: group_path(@conn, :index) %>